---
services:
    fastapi:
        build:
            context: .
            dockerfile: ./Dockerfile
        pull_policy: missing
        image: fastapi
        container_name: fastapi
        ports:
            - 8080:8080
        volumes:
            - ./src:/code/src
        networks:
            - fastapi-network
        depends_on:
            - postgres

    postgres:
        image: postgres:16.2-alpine
        container_name: fastapi-postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - fastapi-network

networks:
    fastapi-network:
        driver: bridge
        name: fastapi-network

volumes:
    db:
        driver: local
